apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deploy.yaml
- service.yaml

helmGlobals:
  chartHome: ./charts

helmCharts:
- name: my-local-chart       # Directory name within chartHome
  releaseName: my-release
  namespace: my-namespace
